### PR TITLE
I made a thing

### PR DESCRIPTION
**Pull request by pahrohfit**
First, great work.

Second, this has some stuff in it:

- Moved to `pytest` for testing (including support for iterating through ORMs)
- Moved to `sanic-testing` for the testing of Sanic to be uniform and supportable
- Moved to `poetry` for package and dependency management
- Bumped the version to `2.0.0_preview_01` just because
- Made the `tortoise-orm` stuff a little more normalized (read: less Tortoise-ish, more whatever)
- Built and bundled in a `umongo` option (what I use)
- Support for bring your own ORM (need to document this, but basically you pass in, via config variables, your Models/Objects which must have a few items)
- Updated all the needed modules to current versions
- Force `username`, as well as `phone` and `email` to be unique, since all can be used to login
- Force role names to be unique, because that's sanity
- Moved model validators into their respective ORM, using their respective best practices
- Started to make the module pluge-able to Sanic, via sanic-ext ... but recent updates broke what was working, and the developers said they are working on overhauling it, so I left it as is for now
- Added some more variables:
```
    "SANIC_SECURITY_ORM": 'tortoise', # Currently supports ['tortoise', 'umongo']
    "SANIC_SECURITY_ACCOUNT": None,
    "SANIC_SECURITY_SESSION": None,
    "SANIC_SECURITY_ROLE": None,
    "SANIC_SECURITY_VERIFICATION_MODEL": None,
    "SANIC_SECURITY_TWOSTEP_MODEL": None,
    "SANIC_SECURITY_CAPTCHA_MODEL": None,
    "SANIC_SECURITY_AUTHENTICATION_MODEL": None,
```

Third, I suck at documentation (including docstrings), and lots is needed, so I'll start working on that next. I tried to maintain as much backwards support as possible .. but some things just needed to change (hence the major version bump) to be sane and relatively clean.

Lastly, the `umongo.py` ORM file still needs some cleanup -- nothing breaking, just code quality and DRYness.

### CODE REVIEW

**Comment by pahrohfit** [comment]
> Wow, this is a lot. Really awesome. Give me some time to check it out.

No worries. Working on the doc updates now.

Still needs:
* unit tests for `custom` provider
* Docs on using `custom` provider, including expectations on necessary properties/functions on them
* Additional fail testing on the security providers

**Comment by sunset-developer** [comment]
> 

I see, will leave this pull request and monitor your changes. Will consider merging when you've completed your version. Thanks!! :)

**Comment by sunset-developer** [comment]
Will do :) gonna provide feedback soon. Thanks!

**Comment by sunset-developer** [comment]
@pahrohfit Sorry if it's taking some time, I've been caught up on work recently and I'm going to make time soon. It's great you've put in work to add more to this project and I appreciate it. Have spent some time reading over it and there's some very interesting changes for sure. Thanks.

**Pull request closed without merging**
